source 'https://rubygems.org'
gem 'sinatra'
gem 'pg'
gem 'heroku'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'oauth2'
gem 'json'
gem 'omniauth'
gem 'omniauth-github'
gem 'pry'
gem 'dotenv'